# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: workshop_chennai_rb_development
  user: udp
  password: udp
  pool: 5
test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: workshop_chennai_rb_development
  user: udp
  password: udp
  pool: 5
