# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  user: <%= ENV["DB_USERNAME"]%>
  password: <%= ENV["DB_PASSWORD"]%>
  pool: 5
  encoding: utf8

development:
  <<: *default
  database: workshop_chennai_rb_development

test:
  <<: *default
  database: workshop_chennai_rb_test
